### ISSUE TITLE
Hacktoberfest 2023 🎉 :  Fix the alignment

### ISSUE THREAD

**Issue by VidhiBhatt01** [Codess-Cafe/Codess-Website#10]
Align the block properly wrt to the logo on the right and social media links on the left

![image](https://github.com/Codess-Cafe/Codess-Website/assets/83345228/5e44a31f-f2db-4a09-893f-65e58817b68c)

**Comment by Reene-Simon** [comment]
Could u please assign this issue to me? I would love to work on this issue as my very first issue.

**Comment by Reene-Simon** [comment]
![Codess Issue](https://github.com/Codess-Cafe/Codess-Website/assets/112744886/c725c6d0-51da-4001-8b79-82db1ae65e75)

![Codess Issue NoBorder](https://github.com/Codess-Cafe/Codess-Website/assets/112744886/8d0bcf4a-2d3b-4f32-a8a8-2931c50f92ee)

Is this alignment okay? The only change made was that the social bar was moved a bit higher to ensure that all are aligned. The image looks like its a bit lower because of the fact that it has some empty area area around the actual color part of the image. 

Another image has been attached which shows the actual view of the page without the outline. Please do let me know if its okay @VidhiBhatt01.

**Comment by Reene-Simon** [comment]
@VidhiBhatt01 yes I got it. I had done that initially but then I wasn't able to align the social bar with the same. I figured it out now.

**Comment by VidhiBhatt01** [comment]
Do we have any updates @Reene-Simon ?

**Comment by Reene-Simon** [comment]
Yeah I'm working on it. Will try to send a PR by tom.

**Comment by VidhiBhatt01** [comment]
That's why you should always link issue in PR description (not in the heading) to avoid such confusion...

**Comment by Reene-Simon** [comment]
Ok di will keep this in mind for all my future contributions. This was my very first contribution.

**Comment by VidhiBhatt01** [comment]
Yes, no worries! You learn on the way only. Keep contributing :)
